# Validates that pull request titles follow the Conventional Commits spec
# (https://www.conventionalcommits.org)
name: PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  conventional-title:
    permissions:
      pull-requests: read
    uses: Merkleye/github-templates/.github/workflows/pr-title.yml@2df9abc1c2797c87571b993498850eced6fdf21b # main
